version: "3"
services:
    beers:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - beers_db
    beers_db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "Supersecret1234"
            ACCEPT_EULA: "Y"
